// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primarybackup/primarybackup.proto

package primarybackup

import (
	fmt "fmt"
	fs3 "github.com/assafvayner/fs3/protos/fs3"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ForwardRequest struct {
	// Types that are valid to be assigned to ClientRequest:
	//	*ForwardRequest_CopyRequest
	//	*ForwardRequest_RemoveRequest
	//	*ForwardRequest_GetRequest
	ClientRequest        isForwardRequest_ClientRequest `protobuf_oneof:"client_request"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ForwardRequest) Reset()         { *m = ForwardRequest{} }
func (m *ForwardRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardRequest) ProtoMessage()    {}
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eecfb583ed99285f, []int{0}
}

func (m *ForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardRequest.Unmarshal(m, b)
}
func (m *ForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardRequest.Marshal(b, m, deterministic)
}
func (m *ForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardRequest.Merge(m, src)
}
func (m *ForwardRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardRequest.Size(m)
}
func (m *ForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardRequest proto.InternalMessageInfo

type isForwardRequest_ClientRequest interface {
	isForwardRequest_ClientRequest()
}

type ForwardRequest_CopyRequest struct {
	CopyRequest *fs3.CopyRequest `protobuf:"bytes,1,opt,name=copy_request,json=copyRequest,proto3,oneof"`
}

type ForwardRequest_RemoveRequest struct {
	RemoveRequest *fs3.RemoveRequest `protobuf:"bytes,2,opt,name=remove_request,json=removeRequest,proto3,oneof"`
}

type ForwardRequest_GetRequest struct {
	GetRequest *fs3.GetRequest `protobuf:"bytes,3,opt,name=get_request,json=getRequest,proto3,oneof"`
}

func (*ForwardRequest_CopyRequest) isForwardRequest_ClientRequest() {}

func (*ForwardRequest_RemoveRequest) isForwardRequest_ClientRequest() {}

func (*ForwardRequest_GetRequest) isForwardRequest_ClientRequest() {}

func (m *ForwardRequest) GetClientRequest() isForwardRequest_ClientRequest {
	if m != nil {
		return m.ClientRequest
	}
	return nil
}

func (m *ForwardRequest) GetCopyRequest() *fs3.CopyRequest {
	if x, ok := m.GetClientRequest().(*ForwardRequest_CopyRequest); ok {
		return x.CopyRequest
	}
	return nil
}

func (m *ForwardRequest) GetRemoveRequest() *fs3.RemoveRequest {
	if x, ok := m.GetClientRequest().(*ForwardRequest_RemoveRequest); ok {
		return x.RemoveRequest
	}
	return nil
}

func (m *ForwardRequest) GetGetRequest() *fs3.GetRequest {
	if x, ok := m.GetClientRequest().(*ForwardRequest_GetRequest); ok {
		return x.GetRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ForwardRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ForwardRequest_CopyRequest)(nil),
		(*ForwardRequest_RemoveRequest)(nil),
		(*ForwardRequest_GetRequest)(nil),
	}
}

type ForwardReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardReply) Reset()         { *m = ForwardReply{} }
func (m *ForwardReply) String() string { return proto.CompactTextString(m) }
func (*ForwardReply) ProtoMessage()    {}
func (*ForwardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_eecfb583ed99285f, []int{1}
}

func (m *ForwardReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardReply.Unmarshal(m, b)
}
func (m *ForwardReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardReply.Marshal(b, m, deterministic)
}
func (m *ForwardReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardReply.Merge(m, src)
}
func (m *ForwardReply) XXX_Size() int {
	return xxx_messageInfo_ForwardReply.Size(m)
}
func (m *ForwardReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ForwardRequest)(nil), "primarybackup.ForwardRequest")
	proto.RegisterType((*ForwardReply)(nil), "primarybackup.ForwardReply")
}

func init() { proto.RegisterFile("primarybackup/primarybackup.proto", fileDescriptor_eecfb583ed99285f) }

var fileDescriptor_eecfb583ed99285f = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd1, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0xe0, 0x06, 0xa4, 0x22, 0x2e, 0x6d, 0xa8, 0x3c, 0xa1, 0x22, 0x24, 0xc8, 0xc4, 0x14,
	0x8b, 0x44, 0x4c, 0x6c, 0x41, 0xa2, 0xac, 0x64, 0x64, 0x41, 0x8e, 0x71, 0x42, 0x44, 0x52, 0x9b,
	0xb3, 0x53, 0xe4, 0x57, 0xe4, 0xa9, 0x10, 0x6e, 0xe5, 0xe0, 0x81, 0xf1, 0xbf, 0xdf, 0xdf, 0x70,
	0x67, 0xb8, 0x56, 0xd8, 0x0d, 0x0c, 0x6d, 0xcd, 0xf8, 0xc7, 0xa8, 0x68, 0x90, 0x32, 0x85, 0xd2,
	0x48, 0xb2, 0x0c, 0x86, 0xeb, 0xd3, 0x46, 0x17, 0xfb, 0x26, 0xfd, 0x8e, 0x20, 0x79, 0x94, 0xf8,
	0xc5, 0xf0, 0xad, 0x12, 0x9f, 0xa3, 0xd0, 0x86, 0xdc, 0xc1, 0x82, 0x4b, 0x65, 0x5f, 0x71, 0x9f,
	0xcf, 0xa3, 0xab, 0xe8, 0x26, 0xce, 0x57, 0xd9, 0x2f, 0x7a, 0x90, 0xca, 0x1e, 0xde, 0x3d, 0xcd,
	0xaa, 0x98, 0x4f, 0x91, 0xdc, 0x43, 0x82, 0x62, 0x90, 0x3b, 0xe1, 0xe1, 0x91, 0x83, 0xc4, 0xc1,
	0xca, 0x55, 0x13, 0x5d, 0xe2, 0xdf, 0x01, 0xc9, 0x21, 0x6e, 0x85, 0xf1, 0xf2, 0xd8, 0xc9, 0x33,
	0x27, 0x37, 0xc2, 0x4c, 0x0c, 0x5a, 0x9f, 0xca, 0x15, 0x24, 0xbc, 0xef, 0xc4, 0xd6, 0xb3, 0x34,
	0x81, 0x85, 0xdf, 0x45, 0xf5, 0x36, 0x7f, 0x86, 0x79, 0xe9, 0x36, 0x26, 0x1b, 0x38, 0x39, 0x34,
	0xe4, 0x32, 0x0b, 0x2f, 0x14, 0x6e, 0xbf, 0xbe, 0xf8, 0xaf, 0x56, 0xbd, 0x4d, 0x67, 0xe5, 0xed,
	0x0b, 0x6d, 0x3b, 0xf3, 0x3e, 0xd6, 0x19, 0x97, 0x03, 0x65, 0x5a, 0xb3, 0x66, 0xc7, 0xec, 0x56,
	0x20, 0x6d, 0x74, 0x41, 0xdd, 0x4d, 0x75, 0xf8, 0x05, 0xf5, 0xdc, 0x4d, 0x8b, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0x20, 0x5d, 0x8a, 0xa8, 0x01, 0x00, 0x00,
}
