FROM assafvayner/fs3:base

COPY keys/jwt/id_ecdsa /keys/id_ecdsa
COPY keys/jwt/id_ecdsa.pub /keys/id_ecdsa.pub

WORKDIR /fs3

RUN go build -o server/auth/authserver server/auth/server.go

COPY keys/grpc-tls/auth/* /certificates

CMD [ "server/auth/authserver" ]