// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/fs3/fs3.proto

package fs3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_GREAT_SUCCESS  Status = 0
	Status_NOT_FOUND      Status = 1
	Status_INTERNAL_ERROR Status = 2
)

var Status_name = map[int32]string{
	0: "GREAT_SUCCESS",
	1: "NOT_FOUND",
	2: "INTERNAL_ERROR",
}

var Status_value = map[string]int32{
	"GREAT_SUCCESS":  0,
	"NOT_FOUND":      1,
	"INTERNAL_ERROR": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{0}
}

type CopyRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileContent          []byte   `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyRequest) Reset()         { *m = CopyRequest{} }
func (m *CopyRequest) String() string { return proto.CompactTextString(m) }
func (*CopyRequest) ProtoMessage()    {}
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{0}
}

func (m *CopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyRequest.Unmarshal(m, b)
}
func (m *CopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyRequest.Marshal(b, m, deterministic)
}
func (m *CopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyRequest.Merge(m, src)
}
func (m *CopyRequest) XXX_Size() int {
	return xxx_messageInfo_CopyRequest.Size(m)
}
func (m *CopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyRequest proto.InternalMessageInfo

func (m *CopyRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *CopyRequest) GetFileContent() []byte {
	if m != nil {
		return m.FileContent
	}
	return nil
}

type RemoveRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{1}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type GetRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type CopyReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyReply) Reset()         { *m = CopyReply{} }
func (m *CopyReply) String() string { return proto.CompactTextString(m) }
func (*CopyReply) ProtoMessage()    {}
func (*CopyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{3}
}

func (m *CopyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyReply.Unmarshal(m, b)
}
func (m *CopyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyReply.Marshal(b, m, deterministic)
}
func (m *CopyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyReply.Merge(m, src)
}
func (m *CopyReply) XXX_Size() int {
	return xxx_messageInfo_CopyReply.Size(m)
}
func (m *CopyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyReply.DiscardUnknown(m)
}

var xxx_messageInfo_CopyReply proto.InternalMessageInfo

func (m *CopyReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_GREAT_SUCCESS
}

func (m *CopyReply) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type RemoveReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReply) Reset()         { *m = RemoveReply{} }
func (m *RemoveReply) String() string { return proto.CompactTextString(m) }
func (*RemoveReply) ProtoMessage()    {}
func (*RemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{4}
}

func (m *RemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReply.Unmarshal(m, b)
}
func (m *RemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReply.Marshal(b, m, deterministic)
}
func (m *RemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReply.Merge(m, src)
}
func (m *RemoveReply) XXX_Size() int {
	return xxx_messageInfo_RemoveReply.Size(m)
}
func (m *RemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReply proto.InternalMessageInfo

func (m *RemoveReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_GREAT_SUCCESS
}

func (m *RemoveReply) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type GetReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileContent          []byte   `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_72eca0a97d8aafb6, []int{5}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_GREAT_SUCCESS
}

func (m *GetReply) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *GetReply) GetFileContent() []byte {
	if m != nil {
		return m.FileContent
	}
	return nil
}

func init() {
	proto.RegisterEnum("fs3.Status", Status_name, Status_value)
	proto.RegisterType((*CopyRequest)(nil), "fs3.CopyRequest")
	proto.RegisterType((*RemoveRequest)(nil), "fs3.RemoveRequest")
	proto.RegisterType((*GetRequest)(nil), "fs3.GetRequest")
	proto.RegisterType((*CopyReply)(nil), "fs3.CopyReply")
	proto.RegisterType((*RemoveReply)(nil), "fs3.RemoveReply")
	proto.RegisterType((*GetReply)(nil), "fs3.GetReply")
}

func init() { proto.RegisterFile("protos/fs3/fs3.proto", fileDescriptor_72eca0a97d8aafb6) }

var fileDescriptor_72eca0a97d8aafb6 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0xf0, 0xa5, 0xa1, 0x53, 0xca, 0x57, 0x27, 0x1e, 0x08, 0x5e, 0xb0, 0x1e, 0x44, 0x62,
	0xc0, 0xc0, 0xdd, 0x04, 0x6b, 0x25, 0x26, 0xd2, 0x9a, 0x2d, 0x5c, 0xbc, 0x34, 0x85, 0x6c, 0x85,
	0xa4, 0xb0, 0xd5, 0x5d, 0x48, 0xf8, 0x0f, 0xfe, 0x68, 0xb3, 0x5b, 0x0d, 0x20, 0x17, 0x0e, 0x1c,
	0x36, 0xd9, 0x7d, 0x6f, 0xf6, 0x65, 0xe6, 0xcd, 0x83, 0xf3, 0xec, 0x93, 0x09, 0xc6, 0x3b, 0x09,
	0xef, 0xc9, 0xd3, 0x56, 0x4f, 0x2c, 0x25, 0xbc, 0xe7, 0x0c, 0xc1, 0x74, 0x59, 0xb6, 0x21, 0xf4,
	0x63, 0x45, 0xb9, 0xc0, 0x0b, 0x30, 0x92, 0x79, 0x4a, 0xa3, 0x2c, 0x16, 0xb3, 0x9a, 0xd6, 0xd0,
	0x9a, 0x06, 0x29, 0x4b, 0xe0, 0x35, 0x16, 0x33, 0xbc, 0x84, 0x8a, 0x22, 0xa7, 0x6c, 0x29, 0xe8,
	0x52, 0xd4, 0x8a, 0x0d, 0xad, 0x59, 0x21, 0xa6, 0xc4, 0xdc, 0x1c, 0x72, 0x6e, 0xc1, 0x22, 0x74,
	0xc1, 0xd6, 0xf4, 0x18, 0x41, 0xe7, 0x06, 0x60, 0x40, 0xc5, 0x51, 0xa5, 0x43, 0x30, 0xf2, 0x3e,
	0xb3, 0x74, 0x83, 0x57, 0xa0, 0x73, 0x11, 0x8b, 0x15, 0x57, 0x65, 0xd5, 0xae, 0xd9, 0x96, 0x53,
	0x85, 0x0a, 0x22, 0x3f, 0xd4, 0xbe, 0x5c, 0xf1, 0x8f, 0x5c, 0x00, 0xe6, 0x6f, 0x9f, 0xa7, 0x11,
	0x64, 0x50, 0x56, 0xa3, 0x9c, 0x44, 0xed, 0xc0, 0xe9, 0xd2, 0x81, 0xd3, 0xad, 0x7b, 0xd0, 0x73,
	0x45, 0x3c, 0x03, 0x6b, 0x40, 0xbc, 0xfe, 0x28, 0x0a, 0xc7, 0xae, 0xeb, 0x85, 0xa1, 0x5d, 0x40,
	0x0b, 0x0c, 0x3f, 0x18, 0x45, 0x4f, 0xc1, 0xd8, 0x7f, 0xb4, 0x35, 0x44, 0xa8, 0x3e, 0xfb, 0x23,
	0x8f, 0xf8, 0xfd, 0x97, 0xc8, 0x23, 0x24, 0x20, 0x76, 0xb1, 0xfb, 0xa5, 0x81, 0x0c, 0x00, 0xb6,
	0xe0, 0x9f, 0x34, 0x16, 0x6d, 0xd5, 0xe4, 0x4e, 0x16, 0xea, 0xd5, 0x1d, 0x24, 0x4b, 0x37, 0x4e,
	0x01, 0xef, 0x40, 0xcf, 0x5d, 0x43, 0x54, 0xdc, 0xde, 0xaa, 0xeb, 0xf6, 0x1e, 0x96, 0xff, 0xb8,
	0x86, 0xd2, 0x80, 0x0a, 0xfc, 0xaf, 0xa8, 0xed, 0xae, 0xeb, 0xd6, 0x16, 0x50, 0x85, 0x0f, 0xce,
	0x5b, 0xe3, 0x7d, 0x2e, 0xd2, 0x78, 0xd2, 0x9e, 0xb2, 0x45, 0x27, 0xe6, 0x3c, 0x4e, 0xd6, 0x2a,
	0xaf, 0xdb, 0xe8, 0x4e, 0x74, 0x75, 0xef, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xac, 0x7c, 0x89,
	0xce, 0xcf, 0x02, 0x00, 0x00,
}
