// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fs3/fs3.proto

package fs3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_UNSPECIFIED    Status = 0
	Status_GREAT_SUCCESS  Status = 1
	Status_NOT_FOUND      Status = 2
	Status_INTERNAL_ERROR Status = 3
	Status_ILLEGAL_PATH   Status = 4
)

var Status_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "GREAT_SUCCESS",
	2: "NOT_FOUND",
	3: "INTERNAL_ERROR",
	4: "ILLEGAL_PATH",
}

var Status_value = map[string]int32{
	"UNSPECIFIED":    0,
	"GREAT_SUCCESS":  1,
	"NOT_FOUND":      2,
	"INTERNAL_ERROR": 3,
	"ILLEGAL_PATH":   4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{0}
}

type CopyRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileContent          []byte   `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyRequest) Reset()         { *m = CopyRequest{} }
func (m *CopyRequest) String() string { return proto.CompactTextString(m) }
func (*CopyRequest) ProtoMessage()    {}
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{0}
}

func (m *CopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyRequest.Unmarshal(m, b)
}
func (m *CopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyRequest.Marshal(b, m, deterministic)
}
func (m *CopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyRequest.Merge(m, src)
}
func (m *CopyRequest) XXX_Size() int {
	return xxx_messageInfo_CopyRequest.Size(m)
}
func (m *CopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyRequest proto.InternalMessageInfo

func (m *CopyRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *CopyRequest) GetFileContent() []byte {
	if m != nil {
		return m.FileContent
	}
	return nil
}

func (m *CopyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RemoveRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{1}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *RemoveRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetRequest struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *GetRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//request used to get a description of document/directory from server
type DescribeRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeRequest) Reset()         { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()    {}
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{3}
}

func (m *DescribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeRequest.Unmarshal(m, b)
}
func (m *DescribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeRequest.Marshal(b, m, deterministic)
}
func (m *DescribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeRequest.Merge(m, src)
}
func (m *DescribeRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeRequest.Size(m)
}
func (m *DescribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeRequest proto.InternalMessageInfo

func (m *DescribeRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DescribeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CopyReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyReply) Reset()         { *m = CopyReply{} }
func (m *CopyReply) String() string { return proto.CompactTextString(m) }
func (*CopyReply) ProtoMessage()    {}
func (*CopyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{4}
}

func (m *CopyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyReply.Unmarshal(m, b)
}
func (m *CopyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyReply.Marshal(b, m, deterministic)
}
func (m *CopyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyReply.Merge(m, src)
}
func (m *CopyReply) XXX_Size() int {
	return xxx_messageInfo_CopyReply.Size(m)
}
func (m *CopyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyReply.DiscardUnknown(m)
}

var xxx_messageInfo_CopyReply proto.InternalMessageInfo

func (m *CopyReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNSPECIFIED
}

func (m *CopyReply) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type RemoveReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReply) Reset()         { *m = RemoveReply{} }
func (m *RemoveReply) String() string { return proto.CompactTextString(m) }
func (*RemoveReply) ProtoMessage()    {}
func (*RemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{5}
}

func (m *RemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReply.Unmarshal(m, b)
}
func (m *RemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReply.Marshal(b, m, deterministic)
}
func (m *RemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReply.Merge(m, src)
}
func (m *RemoveReply) XXX_Size() int {
	return xxx_messageInfo_RemoveReply.Size(m)
}
func (m *RemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReply proto.InternalMessageInfo

func (m *RemoveReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNSPECIFIED
}

func (m *RemoveReply) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

type GetReply struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	FilePath             string   `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileContent          []byte   `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{6}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

func (m *GetReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNSPECIFIED
}

func (m *GetReply) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *GetReply) GetFileContent() []byte {
	if m != nil {
		return m.FileContent
	}
	return nil
}

// reply containing description of file or directory
type DescribeReply struct {
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=fs3.Status" json:"status,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Resource:
	//	*DescribeReply_File_
	//	*DescribeReply_Directory_
	Resource             isDescribeReply_Resource `protobuf_oneof:"resource"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DescribeReply) Reset()         { *m = DescribeReply{} }
func (m *DescribeReply) String() string { return proto.CompactTextString(m) }
func (*DescribeReply) ProtoMessage()    {}
func (*DescribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{7}
}

func (m *DescribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReply.Unmarshal(m, b)
}
func (m *DescribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReply.Marshal(b, m, deterministic)
}
func (m *DescribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReply.Merge(m, src)
}
func (m *DescribeReply) XXX_Size() int {
	return xxx_messageInfo_DescribeReply.Size(m)
}
func (m *DescribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReply proto.InternalMessageInfo

func (m *DescribeReply) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_UNSPECIFIED
}

func (m *DescribeReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type isDescribeReply_Resource interface {
	isDescribeReply_Resource()
}

type DescribeReply_File_ struct {
	File *DescribeReply_File `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type DescribeReply_Directory_ struct {
	Directory *DescribeReply_Directory `protobuf:"bytes,4,opt,name=directory,proto3,oneof"`
}

func (*DescribeReply_File_) isDescribeReply_Resource() {}

func (*DescribeReply_Directory_) isDescribeReply_Resource() {}

func (m *DescribeReply) GetResource() isDescribeReply_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *DescribeReply) GetFile() *DescribeReply_File {
	if x, ok := m.GetResource().(*DescribeReply_File_); ok {
		return x.File
	}
	return nil
}

func (m *DescribeReply) GetDirectory() *DescribeReply_Directory {
	if x, ok := m.GetResource().(*DescribeReply_Directory_); ok {
		return x.Directory
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DescribeReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DescribeReply_File_)(nil),
		(*DescribeReply_Directory_)(nil),
	}
}

type DescribeReply_File struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReply_File) Reset()         { *m = DescribeReply_File{} }
func (m *DescribeReply_File) String() string { return proto.CompactTextString(m) }
func (*DescribeReply_File) ProtoMessage()    {}
func (*DescribeReply_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{7, 0}
}

func (m *DescribeReply_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReply_File.Unmarshal(m, b)
}
func (m *DescribeReply_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReply_File.Marshal(b, m, deterministic)
}
func (m *DescribeReply_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReply_File.Merge(m, src)
}
func (m *DescribeReply_File) XXX_Size() int {
	return xxx_messageInfo_DescribeReply_File.Size(m)
}
func (m *DescribeReply_File) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReply_File.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReply_File proto.InternalMessageInfo

func (m *DescribeReply_File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type DescribeReply_Directory struct {
	Directoryname        string   `protobuf:"bytes,1,opt,name=directoryname,proto3" json:"directoryname,omitempty"`
	Files                []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Subdirectories       []string `protobuf:"bytes,3,rep,name=subdirectories,proto3" json:"subdirectories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReply_Directory) Reset()         { *m = DescribeReply_Directory{} }
func (m *DescribeReply_Directory) String() string { return proto.CompactTextString(m) }
func (*DescribeReply_Directory) ProtoMessage()    {}
func (*DescribeReply_Directory) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb67269a1c8a0734, []int{7, 1}
}

func (m *DescribeReply_Directory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReply_Directory.Unmarshal(m, b)
}
func (m *DescribeReply_Directory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReply_Directory.Marshal(b, m, deterministic)
}
func (m *DescribeReply_Directory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReply_Directory.Merge(m, src)
}
func (m *DescribeReply_Directory) XXX_Size() int {
	return xxx_messageInfo_DescribeReply_Directory.Size(m)
}
func (m *DescribeReply_Directory) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReply_Directory.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReply_Directory proto.InternalMessageInfo

func (m *DescribeReply_Directory) GetDirectoryname() string {
	if m != nil {
		return m.Directoryname
	}
	return ""
}

func (m *DescribeReply_Directory) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *DescribeReply_Directory) GetSubdirectories() []string {
	if m != nil {
		return m.Subdirectories
	}
	return nil
}

func init() {
	proto.RegisterEnum("fs3.Status", Status_name, Status_value)
	proto.RegisterType((*CopyRequest)(nil), "fs3.CopyRequest")
	proto.RegisterType((*RemoveRequest)(nil), "fs3.RemoveRequest")
	proto.RegisterType((*GetRequest)(nil), "fs3.GetRequest")
	proto.RegisterType((*DescribeRequest)(nil), "fs3.DescribeRequest")
	proto.RegisterType((*CopyReply)(nil), "fs3.CopyReply")
	proto.RegisterType((*RemoveReply)(nil), "fs3.RemoveReply")
	proto.RegisterType((*GetReply)(nil), "fs3.GetReply")
	proto.RegisterType((*DescribeReply)(nil), "fs3.DescribeReply")
	proto.RegisterType((*DescribeReply_File)(nil), "fs3.DescribeReply.File")
	proto.RegisterType((*DescribeReply_Directory)(nil), "fs3.DescribeReply.Directory")
}

func init() { proto.RegisterFile("fs3/fs3.proto", fileDescriptor_bb67269a1c8a0734) }

var fileDescriptor_bb67269a1c8a0734 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x05, 0xdb, 0x1f, 0xc2, 0xe3, 0x98, 0xf8, 0x1b, 0x45, 0xaa, 0xe5, 0xf6, 0x90, 0xba, 0x55,
	0x1b, 0x45, 0xaa, 0x13, 0x05, 0xa9, 0x97, 0x56, 0xaa, 0x08, 0x18, 0x82, 0x44, 0x21, 0x5a, 0xe0,
	0xd2, 0x0b, 0x32, 0xce, 0x12, 0xac, 0x12, 0x9b, 0x7a, 0x97, 0x54, 0xfc, 0xbf, 0xfe, 0x86, 0xfe,
	0x9e, 0x6a, 0xd7, 0x05, 0xec, 0xd0, 0x4a, 0x91, 0x9a, 0xdb, 0xee, 0x9b, 0x79, 0x6f, 0xc7, 0x6f,
	0xc6, 0x03, 0xe6, 0x8c, 0xd5, 0xcf, 0x66, 0xac, 0xee, 0x2d, 0xd3, 0x84, 0x27, 0xa8, 0xce, 0x58,
	0xdd, 0x0d, 0xc1, 0x68, 0x26, 0xcb, 0x35, 0xa1, 0xdf, 0x56, 0x94, 0x71, 0x7c, 0x0e, 0xfa, 0x2c,
	0x5a, 0xd0, 0xc9, 0x32, 0xe0, 0x73, 0xbb, 0x7c, 0x5c, 0x3e, 0xd1, 0x49, 0x55, 0x00, 0xd7, 0x01,
	0x9f, 0xe3, 0x4b, 0x38, 0x90, 0xc1, 0x30, 0x89, 0x39, 0x8d, 0xb9, 0xad, 0x1c, 0x97, 0x4f, 0x0e,
	0x88, 0x21, 0xb0, 0x66, 0x06, 0xe1, 0x11, 0xfc, 0xc7, 0x93, 0xaf, 0x34, 0xb6, 0x55, 0xc9, 0xcd,
	0x2e, 0xee, 0x25, 0x98, 0x84, 0xde, 0x25, 0xf7, 0xf4, 0x51, 0xcf, 0x6c, 0x35, 0x94, 0xbc, 0xc6,
	0x27, 0x80, 0x0e, 0xe5, 0xff, 0x20, 0xf0, 0x01, 0x0e, 0x5b, 0x94, 0x85, 0x69, 0x34, 0xdd, 0x96,
	0x81, 0xa0, 0xe5, 0x04, 0xe4, 0xf9, 0x2f, 0xe4, 0xcf, 0xa0, 0x67, 0x36, 0x2d, 0x17, 0x6b, 0x7c,
	0x05, 0x15, 0xc6, 0x03, 0xbe, 0x62, 0x92, 0x58, 0xbb, 0x30, 0x3c, 0x61, 0xea, 0x50, 0x42, 0xe4,
	0x77, 0xa8, 0x58, 0xa1, 0x52, 0xac, 0xd0, 0x1d, 0x80, 0xb1, 0x31, 0xe4, 0x69, 0x04, 0x13, 0xa8,
	0x4a, 0x77, 0x9e, 0x44, 0x6d, 0xaf, 0xd1, 0xea, 0x5e, 0xa3, 0xdd, 0x9f, 0x0a, 0x98, 0x3b, 0x3b,
	0x1f, 0xfd, 0xec, 0xc6, 0x71, 0x25, 0xe7, 0xf8, 0x3b, 0xd0, 0x84, 0xb2, 0x7c, 0xc5, 0xb8, 0x78,
	0x26, 0x69, 0x05, 0x69, 0xaf, 0x1d, 0x2d, 0xe8, 0x55, 0x89, 0xc8, 0x34, 0xfc, 0x08, 0xfa, 0x4d,
	0x94, 0xd2, 0x90, 0x27, 0xe9, 0xda, 0xd6, 0x24, 0xe7, 0xc5, 0x1f, 0x38, 0xad, 0x4d, 0xce, 0x55,
	0x89, 0xec, 0x08, 0x8e, 0x0b, 0x9a, 0x50, 0x43, 0x07, 0xe4, 0xe7, 0xc6, 0xc1, 0x1d, 0xcd, 0xcf,
	0x8f, 0xb8, 0x3b, 0x09, 0xe8, 0x5b, 0x36, 0xbe, 0x06, 0x73, 0xcb, 0xce, 0x65, 0x17, 0x41, 0x31,
	0x35, 0x82, 0xce, 0x6c, 0xe5, 0x58, 0x15, 0x53, 0x23, 0x2f, 0xf8, 0x06, 0x6a, 0x6c, 0x35, 0xdd,
	0x64, 0x46, 0x94, 0xd9, 0xaa, 0x0c, 0x3f, 0x40, 0x2f, 0x01, 0xaa, 0x29, 0x65, 0xc9, 0x2a, 0x0d,
	0xe9, 0x69, 0x00, 0x95, 0xcc, 0x33, 0x3c, 0x04, 0x63, 0xdc, 0x1f, 0x5e, 0xfb, 0xcd, 0x6e, 0xbb,
	0xeb, 0xb7, 0xac, 0x12, 0xfe, 0x0f, 0x66, 0x87, 0xf8, 0x8d, 0xd1, 0x64, 0x38, 0x6e, 0x36, 0xfd,
	0xe1, 0xd0, 0x2a, 0xa3, 0x09, 0x7a, 0x7f, 0x30, 0x9a, 0xb4, 0x07, 0xe3, 0x7e, 0xcb, 0x52, 0x10,
	0xa1, 0xd6, 0xed, 0x8f, 0x7c, 0xd2, 0x6f, 0xf4, 0x26, 0x3e, 0x21, 0x03, 0x62, 0xa9, 0x68, 0xc1,
	0x41, 0xb7, 0xd7, 0xf3, 0x3b, 0x8d, 0xde, 0xe4, 0xba, 0x31, 0xba, 0xb2, 0xb4, 0x8b, 0x1f, 0x65,
	0x50, 0xdb, 0xac, 0x8e, 0xa7, 0xa0, 0x89, 0xa1, 0x46, 0x4b, 0xda, 0x97, 0x5b, 0x03, 0x4e, 0x2d,
	0x87, 0x2c, 0x17, 0x6b, 0xb7, 0x84, 0xe7, 0x50, 0xc9, 0x26, 0x16, 0x51, 0xc6, 0x0a, 0xff, 0xb3,
	0x63, 0x15, 0xb0, 0x8c, 0xf1, 0x16, 0xd4, 0x0e, 0xe5, 0x78, 0x28, 0x43, 0xbb, 0x5f, 0xd7, 0x31,
	0x77, 0x40, 0x96, 0xf8, 0x1e, 0xaa, 0x9b, 0xd6, 0xe1, 0xd1, 0x83, 0x4e, 0x66, 0x14, 0xdc, 0xef,
	0xaf, 0x5b, 0xba, 0x3c, 0xff, 0xe2, 0xdd, 0x46, 0x7c, 0x11, 0x4c, 0xbd, 0x90, 0x79, 0xdf, 0x03,
	0x36, 0x8f, 0xe2, 0x5b, 0x9e, 0xc4, 0x1e, 0xbd, 0x59, 0x9d, 0x05, 0x8c, 0x05, 0xb3, 0x7b, 0xb1,
	0xec, 0xce, 0xe4, 0xb2, 0x63, 0xe2, 0x38, 0xad, 0xc8, 0x73, 0xfd, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x58, 0x4b, 0x61, 0xb9, 0x09, 0x05, 0x00, 0x00,
}
