# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fs3 import fs3_pb2 as fs3_dot_fs3__pb2


class Fs3Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Copy = channel.unary_unary(
                '/fs3.Fs3/Copy',
                request_serializer=fs3_dot_fs3__pb2.CopyRequest.SerializeToString,
                response_deserializer=fs3_dot_fs3__pb2.CopyReply.FromString,
                )
        self.Remove = channel.unary_unary(
                '/fs3.Fs3/Remove',
                request_serializer=fs3_dot_fs3__pb2.RemoveRequest.SerializeToString,
                response_deserializer=fs3_dot_fs3__pb2.RemoveReply.FromString,
                )
        self.Get = channel.unary_unary(
                '/fs3.Fs3/Get',
                request_serializer=fs3_dot_fs3__pb2.GetRequest.SerializeToString,
                response_deserializer=fs3_dot_fs3__pb2.GetReply.FromString,
                )


class Fs3Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def Copy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Fs3Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Copy': grpc.unary_unary_rpc_method_handler(
                    servicer.Copy,
                    request_deserializer=fs3_dot_fs3__pb2.CopyRequest.FromString,
                    response_serializer=fs3_dot_fs3__pb2.CopyReply.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=fs3_dot_fs3__pb2.RemoveRequest.FromString,
                    response_serializer=fs3_dot_fs3__pb2.RemoveReply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=fs3_dot_fs3__pb2.GetRequest.FromString,
                    response_serializer=fs3_dot_fs3__pb2.GetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fs3.Fs3', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Fs3(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Copy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fs3.Fs3/Copy',
            fs3_dot_fs3__pb2.CopyRequest.SerializeToString,
            fs3_dot_fs3__pb2.CopyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fs3.Fs3/Remove',
            fs3_dot_fs3__pb2.RemoveRequest.SerializeToString,
            fs3_dot_fs3__pb2.RemoveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fs3.Fs3/Get',
            fs3_dot_fs3__pb2.GetRequest.SerializeToString,
            fs3_dot_fs3__pb2.GetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
