# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from authservice import authservice_pb2 as authservice_dot_authservice__pb2


class AuthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewUser = channel.unary_unary(
                '/authservice.Auth/NewUser',
                request_serializer=authservice_dot_authservice__pb2.NewUserRequest.SerializeToString,
                response_deserializer=authservice_dot_authservice__pb2.NewUserReply.FromString,
                )
        self.GetToken = channel.unary_unary(
                '/authservice.Auth/GetToken',
                request_serializer=authservice_dot_authservice__pb2.GetNewTokenRequest.SerializeToString,
                response_deserializer=authservice_dot_authservice__pb2.GetNewTokenReply.FromString,
                )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.NewUser,
                    request_deserializer=authservice_dot_authservice__pb2.NewUserRequest.FromString,
                    response_serializer=authservice_dot_authservice__pb2.NewUserReply.SerializeToString,
            ),
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=authservice_dot_authservice__pb2.GetNewTokenRequest.FromString,
                    response_serializer=authservice_dot_authservice__pb2.GetNewTokenReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authservice.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.Auth/NewUser',
            authservice_dot_authservice__pb2.NewUserRequest.SerializeToString,
            authservice_dot_authservice__pb2.NewUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authservice.Auth/GetToken',
            authservice_dot_authservice__pb2.GetNewTokenRequest.SerializeToString,
            authservice_dot_authservice__pb2.GetNewTokenReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
