// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authservice/authservice.proto

package authservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6c6fd2d283aef6, []int{0}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NewUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetNewTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PreviousToken        string   `protobuf:"bytes,3,opt,name=previous_token,json=previousToken,proto3" json:"previous_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNewTokenRequest) Reset()         { *m = GetNewTokenRequest{} }
func (m *GetNewTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetNewTokenRequest) ProtoMessage()    {}
func (*GetNewTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6c6fd2d283aef6, []int{1}
}

func (m *GetNewTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNewTokenRequest.Unmarshal(m, b)
}
func (m *GetNewTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNewTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetNewTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNewTokenRequest.Merge(m, src)
}
func (m *GetNewTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetNewTokenRequest.Size(m)
}
func (m *GetNewTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNewTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNewTokenRequest proto.InternalMessageInfo

func (m *GetNewTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetNewTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetNewTokenRequest) GetPreviousToken() string {
	if m != nil {
		return m.PreviousToken
	}
	return ""
}

type NewUserReply struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Status               *NewUserReply_Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NewUserReply) Reset()         { *m = NewUserReply{} }
func (m *NewUserReply) String() string { return proto.CompactTextString(m) }
func (*NewUserReply) ProtoMessage()    {}
func (*NewUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6c6fd2d283aef6, []int{2}
}

func (m *NewUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserReply.Unmarshal(m, b)
}
func (m *NewUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserReply.Marshal(b, m, deterministic)
}
func (m *NewUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserReply.Merge(m, src)
}
func (m *NewUserReply) XXX_Size() int {
	return xxx_messageInfo_NewUserReply.Size(m)
}
func (m *NewUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserReply proto.InternalMessageInfo

func (m *NewUserReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NewUserReply) GetStatus() *NewUserReply_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type NewUserReply_Status struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserReply_Status) Reset()         { *m = NewUserReply_Status{} }
func (m *NewUserReply_Status) String() string { return proto.CompactTextString(m) }
func (*NewUserReply_Status) ProtoMessage()    {}
func (*NewUserReply_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6c6fd2d283aef6, []int{2, 0}
}

func (m *NewUserReply_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserReply_Status.Unmarshal(m, b)
}
func (m *NewUserReply_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserReply_Status.Marshal(b, m, deterministic)
}
func (m *NewUserReply_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserReply_Status.Merge(m, src)
}
func (m *NewUserReply_Status) XXX_Size() int {
	return xxx_messageInfo_NewUserReply_Status.Size(m)
}
func (m *NewUserReply_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserReply_Status.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserReply_Status proto.InternalMessageInfo

func (m *NewUserReply_Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NewUserReply_Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetNewTokenReply struct {
	Username             string                   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Status               *GetNewTokenReply_Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Token                string                   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetNewTokenReply) Reset()         { *m = GetNewTokenReply{} }
func (m *GetNewTokenReply) String() string { return proto.CompactTextString(m) }
func (*GetNewTokenReply) ProtoMessage()    {}
func (*GetNewTokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6c6fd2d283aef6, []int{3}
}

func (m *GetNewTokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNewTokenReply.Unmarshal(m, b)
}
func (m *GetNewTokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNewTokenReply.Marshal(b, m, deterministic)
}
func (m *GetNewTokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNewTokenReply.Merge(m, src)
}
func (m *GetNewTokenReply) XXX_Size() int {
	return xxx_messageInfo_GetNewTokenReply.Size(m)
}
func (m *GetNewTokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNewTokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNewTokenReply proto.InternalMessageInfo

func (m *GetNewTokenReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetNewTokenReply) GetStatus() *GetNewTokenReply_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetNewTokenReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetNewTokenReply_Status struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNewTokenReply_Status) Reset()         { *m = GetNewTokenReply_Status{} }
func (m *GetNewTokenReply_Status) String() string { return proto.CompactTextString(m) }
func (*GetNewTokenReply_Status) ProtoMessage()    {}
func (*GetNewTokenReply_Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a6c6fd2d283aef6, []int{3, 0}
}

func (m *GetNewTokenReply_Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNewTokenReply_Status.Unmarshal(m, b)
}
func (m *GetNewTokenReply_Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNewTokenReply_Status.Marshal(b, m, deterministic)
}
func (m *GetNewTokenReply_Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNewTokenReply_Status.Merge(m, src)
}
func (m *GetNewTokenReply_Status) XXX_Size() int {
	return xxx_messageInfo_GetNewTokenReply_Status.Size(m)
}
func (m *GetNewTokenReply_Status) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNewTokenReply_Status.DiscardUnknown(m)
}

var xxx_messageInfo_GetNewTokenReply_Status proto.InternalMessageInfo

func (m *GetNewTokenReply_Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetNewTokenReply_Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserRequest)(nil), "authservice.NewUserRequest")
	proto.RegisterType((*GetNewTokenRequest)(nil), "authservice.GetNewTokenRequest")
	proto.RegisterType((*NewUserReply)(nil), "authservice.NewUserReply")
	proto.RegisterType((*NewUserReply_Status)(nil), "authservice.NewUserReply.Status")
	proto.RegisterType((*GetNewTokenReply)(nil), "authservice.GetNewTokenReply")
	proto.RegisterType((*GetNewTokenReply_Status)(nil), "authservice.GetNewTokenReply.Status")
}

func init() { proto.RegisterFile("authservice/authservice.proto", fileDescriptor_6a6c6fd2d283aef6) }

var fileDescriptor_6a6c6fd2d283aef6 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x3f, 0x4f, 0x3a, 0x41,
	0x10, 0xe5, 0x7e, 0x3f, 0x05, 0x1c, 0x94, 0x98, 0x8d, 0xc5, 0x89, 0x21, 0x92, 0x8d, 0x26, 0x36,
	0xde, 0x25, 0xd0, 0x58, 0xd0, 0xa8, 0x05, 0x16, 0x86, 0xe2, 0xd4, 0xc6, 0xc6, 0x2c, 0xe7, 0xf0,
	0x27, 0x0a, 0x7b, 0xee, 0xec, 0x42, 0xf8, 0x28, 0xb6, 0x7e, 0x12, 0x3f, 0x9a, 0x61, 0x8f, 0x23,
	0x0b, 0x11, 0x2c, 0xe8, 0xee, 0xbd, 0x99, 0xbc, 0x79, 0xef, 0xdd, 0x1d, 0x54, 0x85, 0xd1, 0x7d,
	0x42, 0x35, 0x1e, 0xc4, 0x18, 0x3a, 0xcf, 0x41, 0xa2, 0xa4, 0x96, 0xac, 0xe4, 0x50, 0xfc, 0x0e,
	0xca, 0x6d, 0x9c, 0x3c, 0x11, 0xaa, 0x08, 0x3f, 0x0c, 0x92, 0x66, 0x15, 0x28, 0x1a, 0x42, 0x35,
	0x12, 0x43, 0xf4, 0xbd, 0x9a, 0x77, 0xb1, 0x17, 0x2d, 0xf0, 0x6c, 0x96, 0x08, 0xa2, 0x89, 0x54,
	0xaf, 0xfe, 0xbf, 0x74, 0x96, 0x61, 0x4e, 0xc0, 0x5a, 0xa8, 0xdb, 0x38, 0x79, 0x94, 0x6f, 0x38,
	0xda, 0x52, 0x8d, 0x9d, 0x43, 0x39, 0x51, 0x38, 0x1e, 0x48, 0x43, 0x2f, 0x7a, 0x26, 0xe8, 0xff,
	0xb7, 0x1b, 0x07, 0x19, 0x6b, 0xaf, 0xf0, 0x2f, 0x0f, 0xf6, 0x17, 0xfe, 0x93, 0xf7, 0xe9, 0xc6,
	0x7b, 0x57, 0x90, 0x27, 0x2d, 0xb4, 0x21, 0x7b, 0xad, 0x54, 0xaf, 0x05, 0x6e, 0x39, 0xae, 0x4c,
	0xf0, 0x60, 0xf7, 0xa2, 0xf9, 0x7e, 0xa5, 0x09, 0xf9, 0x94, 0x61, 0x3e, 0x14, 0xc8, 0xc4, 0x31,
	0x12, 0x59, 0xf9, 0x62, 0x94, 0xc1, 0xd9, 0x64, 0x88, 0x44, 0xa2, 0x87, 0xf3, 0x30, 0x19, 0xe4,
	0xdf, 0x1e, 0x1c, 0x2e, 0x55, 0xf3, 0x97, 0xd1, 0xe6, 0x8a, 0xd1, 0xb3, 0x25, 0xa3, 0xab, 0x52,
	0x2b, 0x66, 0xd9, 0x11, 0xec, 0xba, 0x8d, 0xa5, 0x60, 0xbb, 0x08, 0xf5, 0x4f, 0x0f, 0x76, 0xae,
	0x8d, 0xee, 0xb3, 0x5b, 0x28, 0xcc, 0x8b, 0x62, 0x27, 0xbf, 0xd7, 0x67, 0xdf, 0x7b, 0xe5, 0x78,
	0x6d, 0xb7, 0x3c, 0xc7, 0xee, 0xa1, 0xd8, 0x42, 0x6d, 0x13, 0xb0, 0xd3, 0xf5, 0xd9, 0x52, 0xa5,
	0xea, 0xc6, 0xf0, 0x3c, 0x77, 0x13, 0x3e, 0x5f, 0xf6, 0x06, 0xba, 0x6f, 0x3a, 0x41, 0x2c, 0x87,
	0xa1, 0x20, 0x12, 0xdd, 0xb1, 0x98, 0x8e, 0x50, 0x85, 0x5d, 0x6a, 0x84, 0xf6, 0x9b, 0x27, 0xf7,
	0x37, 0xe8, 0xe4, 0x2d, 0xd7, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x73, 0x38, 0x95, 0x31, 0x28,
	0x03, 0x00, 0x00,
}
